# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncmxpof', '0002_auto_20171122_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncm',
            name='pof',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ncmxpof.Pof'),
            preserve_default=False,
        ),
    ]
