# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncmxpof', '0003_ncm_pof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncm',
            name='descript',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pof',
            name='descript',
            field=models.CharField(max_length=500),
        ),
    ]
