# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncmxpof', '0005_auto_20171129_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncm',
            name='descript',
            field=models.CharField(max_length=1000),
        ),
    ]
